all:
	java -cp ../antlr-3.5.2-complete-no-st3.jar org.antlr.Tool myCompiler.g
	javac -cp ../antlr-3.5.2-complete-no-st3.jar myCompilerLexer.java myCompilerParser.java myCompiler_test.java

clean:
	rm *.class

