all:
	java -cp ../antlr-3.5.2-complete-no-st3.jar org.antlr.Tool myChecker.g
	javac -cp ../antlr-3.5.2-complete-no-st3.jar myCheckerLexer.java myCheckerParser.java myChecker_test.java

clean:
	rm *.class

